config/routes.rb
Rails.application.routes.draw do
  get 'appointments/index'

  root to: 'appointments#index'

  resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	validates :Name, presence: true
	validates :Last_name, presence: true
	validates :Phone_number, presence: true
	validates :Date, presence: true
	validates :Time, presence: true

	default_scope { order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new(params[:id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:success] = "Appointment has been created"
      redirect_to appointments_path
    else 
      flash.now[:danger] = "Appointment has not been created"
      render :new
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
     @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      flash[:success] = "Appointment has been updated"
      redirect_to appointments_path
    else
      flash.now[:danger] = "Appointment has not been update"
      render :edit
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    if @appointment.destroy
      flash[:success] = "Appointment has been deleted"
      redirect_to appointments_path
    end
  end


  private

  def appointment_params
    params.require(:appointment).permit(:Name, :Last_name, :Phone_number, :Date, :Time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.html.erb
<h3 class='text-center'>Edit Appointment</h3>
<div class='row'>
  <div class='col-md-12'>
    <%= form_for(@appointment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @appointment.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
          <%= pluralize(@appointment.errors.count, "error") %>
          prohibited this appointment from being saved:
          </h2>

          <div class="panel-body">
            <ul>
              <% @appointment.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
    </div>
    <% end %>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Name %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Name, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Last_name %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Last_name, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Phone_number %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Phone_number, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Date %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Date, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Time %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Time, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

 

    <div class='form-group'>
      <div class='col-md-offset-1 col-md-11'>
        <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/appointments/index.html.erb
<h1>Listing all Appointments</h1>

<%= link_to "New appointment", new_appointment_path, class: "btn btn-default btn-lg", id: "new-appointment-btn" %>

<% @appointments.each do |appointment| %>
	<div class="well well-lg">
		<div class="appointment-Name">
			<%= link_to appointment.Name, appointment_path(appointment) %>
		</div>

		<div class="appointment-Date">
			<%= appointment.Date %>
		</div>
	</div>
<% end %>

app/views/appointments/new.html.erb
<h3 class='text-center'>Making a new Appointment</h3>
<div class='row'>
  <div class='col-md-12'>
    <%= form_for(@appointment, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @appointment.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
          <%= pluralize(@appointment.errors.count, "error") %>
          prohibited this appointment from being saved:
          </h2>

          <div class="panel-body">
            <ul>
              <% @appointment.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
    </div>
    <% end %>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Name %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Name, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Last_name %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Last_name, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Phone_number %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Phone_number, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Date %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Date, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

    <div class='form-group'>
      <div class='control-label col-md-1'>
        <%= f.label :Time %>
      </div>
      <div class='col-md-11'>
        <%= f.text_field :Time, class: 'form-control', placeholder: '', autofocus: true %>
      </div>
    </div>

 

    <div class='form-group'>
      <div class='col-md-offset-1 col-md-11'>
        <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/appointments/show.html.erb
<h1><%= @appointment.Name %>'s details</h1>
  
  <p>
    Name: <%= @appointment.Name %>
  </p>

  <p>
    Last name: <%= @appointment.Last_name %>
  </p>

  <p>
    Phone number: <%= @appointment.Phone_number %>
  </p>

  <p>
    Date: <%= @appointment.Date %>
  </p>

  <p>
    Time: <%= @appointment.Time.strftime("%I:%M %p") %>
  </p>

  <%= link_to "Back", appointments_path, class: "btn btn-primary btn-lg btn-space" %>
  <%= link_to "Edit appointment", edit_appointment_path, class: "btn btn-primary btn-lg btn-space" %>
  <%= link_to "Delete appointment", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-lg btn-space" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarberApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Barber App", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Authors", "#" %></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href= '#' class='close' data-dismiss='alert' &#215;></a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-8">
        <%= yield %>
      </div>

      <div class="col-md-4">
        <%= yield :sidebar %>
      </div>
    </div>
  </div>
        




</body>
</html>